In [2]:
import pandas as pd

sasubset = pd.read_csv("SAsubset.csv")

In [ ]:
sasubset

In [ ]:
sasubset['SentimentText']

## Using pandas as your new excel

In [16]:
nte = pd.read_csv("nte.csv")

In [17]:
nte

code                            cname  \
0    N0101                香海正覺蓮社佛教馬錦燦紀念英文中學   
1    N0201                           粉嶺公立學校   
2    N0202                        明愛粉嶺陳震夏中學   
3    N0301                           祥華社區會堂   
4    N0401                   香海正覺蓮社佛教正覺蓮社學校   
5    N0501                        鳳溪廖潤琛紀念學校   
6    N0601                     香海正覺蓮社佛教普光學校   
7    N0602                   路德會賽馬會雍盛綜合服務中心   
8    N0701                        聖公會嘉福榮真小學   
9    N0801                           粉嶺官立中學   
10   N0802                            田家炳中學   
11   N0901                   風采中學(教育評議會主辦)    
12   N1001                           保榮路體育館   
13   N1101                          金錢村何東學校   
14   N1102                            蕉徑村公所   
15   N1103                         古洞公立愛華學校   
16   N1104                            坑頭村公所   
17   N1201                             彩園會堂   
18   N1301                           龍琛路體育館   
19   N1302                          聖公會陳融中學   
20   N1303                    香海正覺蓮社佛教陳式宏學校   
21   N1401                          石湖墟公立學校   
22   N1501                         鳳溪廖萬石堂中學   
23   N1601                        打鼓嶺嶺英公立學校   
24   N1602  International College Hong Kong   
25   N1604                          沙頭角中心小學   
26   N1606                          打鼓嶺社區會堂   
27   N1701                            天平體育館   
28   N1702                          聯和墟社區會堂   
29   N1801                             從謙學校   
..     ...                              ...   
113  R1602                             才俊學校   
114  R1701                           隆亨社區中心   
115  R1801                      東莞工商總會張煌偉小學   
116  R1901                          佛教黃允畋中學   
117  R1902                           大圍村村公所   
118  R2001                             樂道中學   
119  R2002                  基督教香港信義會沙田信義幼稚園   
120  R2101                         保良局蕭漢森小學   
121  R2201                          賽馬會體藝中學   
122  R2301                       香港中文大學富爾敦樓   
123  R2302                  仁愛堂香港台山商會長者活動中心   
124  R2401                       宣道會台山陳元喜小學   
125  R2501                 香港中文大學校友會聯會陳震夏中學   
126  R2601                      香港道教聯合會純陽小學   
127  R2801                          明愛馬鞍山中學   
128  R2901                           利安社區會堂   
129  R3001                     吳氏宗親總會泰伯紀念學校   
130  R3002                        東華三院黃鳳翎中學   
131  R3101                         保良局莊啟程小學   
132  R3201                         馬鞍山聖若瑟小學   
133  R3202                           恒安社區中心   
134  R3301                             德信中學   
135  R3401                       聖公會馬鞍山主風小學   
136  R3402                  基督教香港信義會馬鞍山信義學校   
137  R3501                            林大輝中學   
138  R3601                         路德會梁鉅鏐小學   
139  R3602                 香港浸會大學附屬學校王錦輝中小學   
140  R3701                      世界龍岡學校黃耀南小學   
141  R3801                           廣源社區會堂   
142  LC005                 亞洲國際博覽館 (點算誤投選票)   

                                                 ename  方國珊  林卓廷  廖添誠  陳云根  \
0    HHCKLA Buddhist Ma Kam Chan Memorial English S...  158  321   23  132   
1                                Fanling Public School   58  101    4   46   
2        Caritas Fanling Chan Chun Ha Secondary School   93  185    4  101   
3                            Cheung Wah Community Hall  198  971   16  249   
4     HHCKLA Buddhist Ching Kok Lin Association School  289  497   11  326   
5                 Fung Kai Liu Yun Sum Memorial School  185  234   24  309   
6                      HHCKLA Buddhist Po Kwong School  110  246    7  138   
7    Jockey Club Yung Shing Lutheran Integrated Ser...  110  205    8  204   
8                  SKH Ka Fuk Wing Chun Primary School  248  363    9  230   
9                  Fanling Government Secondary School  163  242    7   96   
10                        Tin Ka Ping Secondary School   80  187    2   89   
11   Elegantia College (Sponsored by Education Conv...  169  309    9  215   
12                          Po Wing Road Sports Centre  104  307    8  173   

In [18]:
nte['陳云根']

0      132
1       46
2      101
3      249
4      326
5      309
6      138
7      204
8      230
9       96
10      89
11     215
12     173
13      39
14      15
15      53
16      32
17     244
18      31
19     128
20      70
21     241
22     182
23      14
24      30
25      38
26      24
27     190
28     192
29      40
      ... 
113     47
114    225
115    228
116    202
117     56
118    166
119     17
120    196
121    154
122     24
123     84
124    253
125    266
126    222
127    307
128    406
129    171
130     98
131    334
132    185
133    131
134    255
135    293
136     43
137    283
138    154
139     49
140    282
141    233
142      1
Name: 陳云根, dtype: int64

In [19]:
nte.iloc[1]

code                     N0201
cname                   粉嶺公立學校
ename    Fanling Public School
方國珊                         58
林卓廷                        101
廖添誠                          4
陳云根                         46
梁國雄                        118
張超雄                        127
楊岳橋                        131
麥嘉晉                         16
鄭家富                         32
葛珮帆                         79
侯志強                        307
李梓敬                         48
鄧家彪                         55
范國威                         36
陳玉娥                          2
黃琛喻                          4
李偲嫣                         27
陳志全                        120
梁頌恆                         94
梁金成                          3
容海恩                         72
陳克勤                        190
Name: 1, dtype: object

In [ ]:
nte.iloc[:,1]

In [ ]:
nte.iloc[:,3]

In [ ]:
nte.iloc[:,3:24]

In [ ]:
nte.iloc[:,3:24].sum(0)

In [ ]:
nte.iloc[:,3:24].sum(0)

In [ ]:
nte.iloc[:,3:24].sum(0).sort_values()

In [ ]:
nte.iloc[:,3:24].sum(1)

In [ ]:
nte.iloc[:,3:24].div(nte.iloc[:,3:24].sum(1), axis = 0)

In [ ]:
nte.iloc[:,3:24].div(nte.iloc[:,3:24].sum(1), axis = 0)['梁國雄']

In [ ]:
nte.iloc[:,3:24].div(nte.iloc[:,3:24].sum(1), axis = 0)['梁國雄'] * 100

In [13]:
X = nte.iloc[:,3:24].div(nte.iloc[:,3:24].sum(1), axis = 0)
X

方國珊       林卓廷       廖添誠       陳云根       梁國雄       張超雄       楊岳橋  \
0    0.060398  0.122706  0.008792  0.050459  0.076453  0.115443  0.118502   
1    0.039189  0.068243  0.002703  0.031081  0.079730  0.085811  0.088514   
2    0.052811  0.105054  0.002271  0.057354  0.074957  0.126065  0.101079   
3    0.040416  0.198204  0.003266  0.050827  0.077159  0.088998  0.088794   
4    0.055037  0.094649  0.002095  0.062083  0.079604  0.103028  0.110455   
5    0.036296  0.045909  0.004709  0.060624  0.094369  0.083775  0.101825   
6    0.045212  0.101110  0.002877  0.056720  0.076860  0.109741  0.117961   
7    0.035065  0.065349  0.002550  0.065030  0.082563  0.111890  0.111890   
8    0.048438  0.070898  0.001758  0.044922  0.072461  0.103711  0.086133   
9    0.063597  0.094421  0.002731  0.037456  0.067889  0.122903  0.119001   
10   0.046976  0.109806  0.001174  0.052261  0.054022  0.095126  0.093952   
11   0.051166  0.093551  0.002725  0.065092  0.095065  0.090524  0.099304   
12   0.027645  0.081606  0.002127  0.045986  0.053429  0.070973  0.073099   
13   0.032653  0.065306  0.000000  0.031837  0.066122  0.056327  0.088980   
14   0.043646  0.078306  0.000000  0.019255  0.078306  0.050064  0.075738   
15   0.039151  0.069675  0.001991  0.035169  0.065693  0.068348  0.078965   
16   0.081967  0.094262  0.001025  0.032787  0.070697  0.063525  0.084016   
17   0.047242  0.131103  0.001582  0.055154  0.087703  0.088834  0.086573   
18   0.032095  0.241554  0.000000  0.052365  0.062500  0.052365  0.072635   
19   0.038307  0.231302  0.002919  0.046698  0.069683  0.069318  0.082452   
20   0.049784  0.281385  0.000722  0.050505  0.064935  0.089466  0.064214   
21   0.030534  0.129771  0.001032  0.049721  0.080875  0.089746  0.109346   
22   0.043642  0.096175  0.001616  0.049030  0.077047  0.076509  0.114494   
23   0.025974  0.090909  0.000000  0.030303  0.069264  0.054113  0.071429   
24   0.033386  0.077901  0.000000  0.047695  0.066773  0.049285  0.095390   
25   0.143552  0.051095  0.003650  0.046229  0.092457  0.070560  0.120438   
26   0.035115  0.068702  0.001527  0.036641  0.062595  0.141985  0.106870   
27   0.034853  0.134048  0.001340  0.063673  0.078083  0.093164  0.117292   
28   0.057895  0.093629  0.005817  0.053186  0.075069  0.113850  0.114681   
29   0.122558  0.065719  0.005329  0.071048  0.072824  0.069272  0.103020   
..        ...       ...       ...       ...       ...       ...       ...   
113  0.047891  0.099357  0.001430  0.033595  0.048606  0.099357  0.105790   
114  0.041584  0.056766  0.001100  0.049505  0.079868  0.088449  0.079648   
115  0.055419  0.051636  0.001513  0.043125  0.073009  0.082656  0.070550   
116  0.037226  0.054192  0.000824  0.033273  0.058310  0.078735  0.086312   
117  0.070555  0.049859  0.001881  0.052681  0.071496  0.090310  0.099718   
118  0.049865  0.071525  0.002256  0.037455  0.056859  0.096796  0.098375   
119  0.031915  0.065603  0.001773  0.030142  0.047872  0.088652  0.097518   
120  0.040520  0.084289  0.001911  0.037462  0.060780  0.093272  0.150803   
121  0.036893  0.067022  0.000820  0.031564  0.055954  0.110883  0.110064   
122  0.037428  0.082534  0.000000  0.023033  0.068138  0.130518  0.077735   
123  0.041247  0.091048  0.002444  0.025665  0.040941  0.116101  0.113963   
124  0.026020  0.059900  0.002710  0.034286  0.055834  0.138501  0.080499   
125  0.033021  0.068815  0.001453  0.035134  0.062871  0.133272  0.089816   
126  0.041508  0.069867  0.002852  0.035171  0.056559  0.134030  0.111534   
127  0.028987  0.095480  0.002840  0.036323  0.055963  0.101159  0.096190   
128  0.032982  0.073551  0.001370  0.042782  0.061538  0.105690  0.099895   
129  0.029751  0.079336  0.002076  0.039437  0.057426  0.098017  0.104013   
130  0.038842  0.088728  0.003427  0.037319  0.052932  0.120716  0.114623   
131  0.032032  0.074374  0.002062  0.045917  0.073275  0.120291  0.095271   
132  0.030400  0.120531  0.001927  0.039606  0.077928  0.111753  0.083922   
133  0

### Clustering the voting stations

In [5]:
import numpy as np

In [ ]:
X.as_matrix

In [20]:
from sklearn.cluster import KMeans

In [21]:
hx_km = KMeans(n_clusters = 2)

In [22]:
hx_km.fit(X.values)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [23]:
hx_km.predict(X.values)

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int32)

In [28]:
nte['cname'][hx_km.predict(X.values)==0] ### What so special about these stations?

1                              粉嶺公立學校
13                            金錢村何東學校
14                              蕉徑村公所
15                           古洞公立愛華學校
16                              坑頭村公所
22                           鳳溪廖萬石堂中學
23                          打鼓嶺嶺英公立學校
24    International College Hong Kong
25                            沙頭角中心小學
26                            打鼓嶺社區會堂
30                               龍山學校
53                             泰亨公立學校
Name: cname, dtype: object

In [30]:
X[hx_km.predict(X.values)==0].mean(0)

方國珊    0.051348
林卓廷    0.074191
廖添誠    0.001043
陳云根    0.035734
梁國雄    0.071547
張超雄    0.075257
楊岳橋    0.091888
麥嘉晉    0.008439
鄭家富    0.025493
葛珮帆    0.046062
侯志強    0.228191
李梓敬    0.034708
鄧家彪    0.029588
范國威    0.029213
陳玉娥    0.001931
黃琛喻    0.003298
李偲嫣    0.009414
陳志全    0.080019
梁頌恆    0.065988
梁金成    0.001363
容海恩    0.035285
dtype: float64

In [31]:
## Evaluation

from sklearn.metrics import silhouette_score
print silhouette_score(X.values, hx_km.predict(X.values))

0.389590606587


In [32]:
hx_km = KMeans(n_clusters = 3)
hx_km.fit(X.values)
print silhouette_score(X.values, hx_km.predict(X.values))

0.26953278068


### Clustering the participants

In [33]:
X.values.shape

(143, 21)

In [34]:
X.values.transpose()

array([[ 0.06039755,  0.03918919,  0.0528109 , ...,  0.03177711,
         0.02782324,  0.11320755],
       [ 0.12270642,  0.06824324,  0.10505395, ...,  0.07018072,
         0.04684943,  0.05660377],
       [ 0.00879205,  0.0027027 ,  0.00227144, ...,  0.00180723,
         0.00163666,  0.01886792],
       ..., 
       [ 0.09441896,  0.06351351,  0.09483248, ...,  0.05843373,
         0.075491  ,  0.        ],
       [ 0.00152905,  0.00202703,  0.00113572, ...,  0.0003012 ,
         0.00020458,  0.        ],
       [ 0.0382263 ,  0.04864865,  0.03463941, ...,  0.0936747 ,
         0.19353519,  0.0754717 ]])

In [35]:
X.values.transpose().shape

(21, 143)

In [36]:
hx_km = KMeans(n_clusters = 2)

hx_km.fit(X.values.transpose())
hx_km.predict(X.values.transpose())

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1], dtype=int32)

In [ ]:
nte.columns.values[3:24]

In [37]:
for name in nte.columns.values[3:24][hx_km.predict(X.values.transpose())==0]:
    print name

廖添誠
麥嘉晉
鄭家富
侯志強
李梓敬
陳玉娥
黃琛喻
李偲嫣
梁金成


In [38]:
for name in nte.columns.values[3:24][hx_km.predict(X.values.transpose())==1]:
    print name

方國珊
林卓廷
陳云根
梁國雄
張超雄
楊岳橋
葛珮帆
鄧家彪
范國威
陳志全
梁頌恆
容海恩
